project:
  type: website

website:
  title: "markupsite2023"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: cooperation.qmd
        text: Cooperation

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true



