---
title: "CV"
format:
  html:
    css: styles.css
---

## Skills

**Analytic & Statistical Methods**

<ul style="margin-top:0em; margin-bottom:0em;">
  <li style="margin-bottom:0.15em;">Statistical Inference</li>
  <li style="margin-bottom:0.15em;">Regression Analysis</li>
  <li style="margin-bottom:0.15em;">Machine Learning</li>
  <li style="margin-bottom:0.15em;">Natural Language Processing (NLP)</li>
  <li style="margin-bottom:0.15em;">Experimental and Quasi-experimental Designs</li>
  <li style="margin-bottom:0.15em;">Survey Design</li>
</ul>

<div style="height:0.7em;"></div>

**Programming**

<ul style="margin-top:0em; margin-bottom:0em;">
  <li style="margin-bottom:0.15em;">R (tidyverse, data.table, dplyr, brms, lavaan, semTools, mice, ggplot2, Shiny, caret, randomForest, lubridate, readr)</li>
  <li style="margin-bottom:0.15em;">Python (pandas, numpy, scipy, matplotlib, seaborn, scikit-learn, statsmodels, plotly, pyspark.sql, xgboost, tensorflow)</li>
  <li style="margin-bottom:0.15em;">SQL (MySQL)</li>
  <li style="margin-bottom:0.15em;">HTML</li>
</ul>

<div style="height:0.7em;"></div>

**Business Intelligence & Visualization**

<ul style="margin-top:0em; margin-bottom:0em;">
  <li style="margin-bottom:0.15em;">Power BI</li>
  <li style="margin-bottom:0.15em;">Custom Python & R visualizations</li>
  <li style="margin-bottom:0.15em;">DAX, Power Query</li>
</ul>

<div style="height:0.7em;"></div>

**Cloud & Workflow Tools**

<ul style="margin-top:0em; margin-bottom:0em;">
  <li style="margin-bottom:0.15em;">Microsoft Fabric (Azure Data Lake, Engineering, Data Factory)</li>
  <li style="margin-bottom:0.15em;">Microsoft Office (Excel – advanced, Word, PowerPoint)</li>
  <li style="margin-bottom:0.15em;">Git (GitHub)</li>
  <li style="margin-bottom:0.15em;">Jira, Asana, Confluence</li>
  <li style="margin-bottom:0.15em;">LaTeX (Overleaf)</li>
  <li style="margin-bottom:0.15em;">SPSS, Mplus</li>
</ul>

## Experience

**Business Analyst** \| Data Analytics Department \| *Dec 2024 - Ongoing* \| BartsParts B.V.

I lead the design and rollout of data-driven solutions supporting key business objectives in the e-commerce sector. My work centers on transforming complex data flows into dashboards and actionable insights.

<ul style="margin-top:0em; margin-bottom:0em;"> 
  <li style="margin-bottom:0.15em;"> Designed and implemented scalable data pipelines using Microsoft Fabric and Azure, integrating raw data from sales, logistics, customer support, and IT networks.</li> 
  <li style="margin-bottom:0.15em;"> Built and deployed near-real-time Power BI dashboards tailored for Sales, Supply Chain, and Management teams, boosting data visibility and decision speed.</li> 
  <li style="margin-bottom:0.15em;">Identified, analyzed, and resolved critical data gaps to improve data quality and reporting accuracy across the organization.</li> 
  <li style="margin-bottom:0.15em;">Collaborated cross-functionally to automate data workflows and embed analytics in daily operations, delivering measurable efficiency improvements.</li> 
</ul>

<div style="height:0.7em;"></div>

**Junior Business Analyst** \| Data Analytics Department \| *June 2024 - Dec 2024* \| BartsParts B.V.

I supported the unification of company data infrastructure and laid the groundwork for business analytics initiatives. My main responsibilities included connecting diverse data sources, preprocessing datasets, and developing custom visualizations.

<ul style="margin-top:0em; margin-bottom:0em;"> 
  <li style="margin-bottom:0.15em;">Connected and consolidated data from multiple systems using SQL, SparkR, and PySpark preparing data for unified analysis.</li> 
  <li style="margin-bottom:0.15em;">Created custom data visualizations in R to address specific business needs and improve reporting clarity.</li> 
  <li style="margin-bottom:0.15em;">Collaborated with analysts and department leaders to understand reporting requirements and deliver timely, actionable insights.</li> 
</ul>
  
<div style="height:0.7em;"></div>

**Research & Teaching Assistant** \| Department of Methodology and Statistics \| *Aug 2023 - June 2024* \| Utrecht University

<ul style="margin-top:0em; margin-bottom:0em;"> 
  <li style="margin-bottom:0.15em;">Explored packages for Bayesian exploratory factor analysis (EFA) currently available in R and prepared a framework for a simulation study.</li> 
  <li style="margin-bottom:0.15em;">Assisted students to understand foundations of survey-based research & master R usage for survey data analysis.</li> 
</ul>

<div style="height:0.7em;"></div>

**Research Assistant** \| Department of Politics and Governance \| *Feb 2022 - Sept 2022* \| Higher School of Economics

<ul style="margin-top:0em; margin-bottom:0em;"> 
  <li style="margin-bottom:0.15em;">Integrated, cleaned, and managed multiple large datasets using R and Python to support quantitative research on COVID-19’s impact. </li> 
  <li style="margin-bottom:0.15em;">Contributed to data preparation, literature review, and the quantitative analysis of policy outcomes. </li> 
  <li style="margin-bottom:0.15em;">Applied statistical analysis to identify patterns and prepared reports for a cross-disciplinary research team. </li> 
</ul>


<div style="height:0.7em;"></div>

**Trainee Researcher** \| Ronald F. Inglehart Laboratory for Comparative Social Research \| *Feb 2021 - Feb 2022* \| Higher School of Economics

<ul style="margin-top:0em; margin-bottom:0em;"> 
  <li style="margin-bottom:0.15em;">Sourced, cleaned, and managed complex quantitative datasets for large-scale comparative studies, ensuring data quality and consistency. </li> 
  <li style="margin-bottom:0.15em;">Performed statistical analysis and built structural equation models (SEM) in R to validate research hypotheses and support data-driven recommendations. </li> 
</ul>

<div style="height:0.7em;"></div>

**Junior Analyst** \| Holding "Minchenko Consulting" \| *Jul 2020 - Feb 2022* 

<ul style="margin-top:0em; margin-bottom:0em;"> 
  <li style="margin-bottom:0.15em;">Parsed and mined large volumes of data from social and traditional media platforms & search engines to extract trends in public representation. </li> 
  <li style="margin-bottom:0.15em;">Transformed unstructured text data into clear metrics and developed typologies using both qualitative and quantitative methods. </li> 
  <li style="margin-bottom:0.15em;">Co-authored and published a research paper based on this project in a Q1-ranked academic journal.</li> </ul> <div style="height:0.7em;"></div>
</ul>

<div style="height:0.7em;"></div>

**Teaching Assistant** \| Higher School of Economics \| *Oct 2020 - Jun 2021*

<ul style="margin-top:0em; margin-bottom:0em;"> 
  <li style="margin-bottom:0.15em;">Assisted first and second-year students with R, LaTeX, and probability theory. </li> 
  <li style="margin-bottom:0.15em;">Reviewed assignments and provided individual consultations to support course objectives in mathematics and politics.</li> 
</ul>


## Education

**UTRECHT UNIVERSITY, UTRECHT** \| MSc in Methodology and Statistics for the Behavioural, Biomedical and Social Sciences \| *Track: Applied Data Science* \| 2022-2024

• Focused on machine learning, NLP, clustering, and survey data analysis. Thesis examined error sources in survey data linked to donated digital trace data, developing methods to reduce bias from selective participation.

**HIGHER SCHOOL OF ECONOMICS, MOSCOW** \| BSc in Political Science \| *Track: Political Analysis* \| 2018-2022

• Graduated with honors (GPA: 8.9). Specialized in quantitative methods, including multilevel modeling, time-series analysis, and structural equation modeling.

**VCIOM SOCIOLOGIC SCHOOL, MOSCOW** \| Winter School \| *Track: Policy and Market Analysis* \| 2022

• Focused on advanced survey design and data collection methodologies, with practical applications to policy evaluation and market research.

**DULWICH COLLEGE, LONDON** \| Summer School \| *Track: Global Young Leaders* \| 2017

• Graduated with honors (A). Engaged in interdisciplinary study of international relations, communication, and economics, developing strong analytic and leadership skills.

## Achievements

• Utrecht Excellence Scholarship recipient \| *2022-2024*

• Olympiad "Higher League" winner - "Politics, Economics, Philosophy" track \| *2021*

• Top-2 student rating of the Political Science programme, twice \| *2018-2019*

• Personal scholarship of the Moscow Government \| *2018-2019*

## Publications

• Kozlov, V., Romanov, D., Balalaeva, D., & Fominykh, I. (2025). Youth indoctrination in Russia: Will it achieve loyalty or hatred? Available at SSRN 5264533.

• Petrov, K., Fominykh, I., Bakshuk, M., Ahalian, A., & Krasnikov, A. (2024). The rise of tech illiberalism in Russia: E-voting and new dimensions of securitization. Journal of Illiberalism Studies, 4(3), 51–71. 

• Romanov, D., Fominykh, I., & Ankudinov, I. (2023). Substituting the Opposition under Electoral Authoritarianism: The Case of the Russian Regional Parliamentary Elections in 2021. Russian Politics, 8(4), 519-549.

• Fominykh I. G., Petrov K. Y. (2021) Spouses of Russian Governors and Their Self-Representation Strategies: Celebrities or Housewives? Monitoring of Public Opinion: Economic and Social Changes, (5), 138--162. (In Russ.)

## Conferences

• **ODISSEI Conference for Computational Social Science** \| Presenter \| *2024* \| Utrecht, Netherlands

• **2nd Conference "New Advances in the Political Economy of Development in Eurasia"** \| Presenter \| *2024* \| Almaty, Kazakhstan
